CREATE TYPE service_type_enum AS ENUM (
    'Agents',
    'Microsoft Apps',
    'Websites',
    'Products',
    'Web & Mobile App'
);

CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" character varying(120) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "MobileNumber" character varying(16) NOT NULL,
    "ServiceType" service_type_enum DEFAULT 'Agents'::service_type_enum NOT NULL,
    "ProjectGoal" text NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
